### ISSUE TITLE
Add Things Dammit

### ISSUE THREAD

**Issue by DesBlock** [DesBlock/Learn-PipeTo-Remember#1]
Just do it!
![image](https://cloud.githubusercontent.com/assets/7647070/16456103/b3e3c89a-3de4-11e6-9f88-83353406e594.png)

**Comment by ACKmySYN** [comment]
Added to your todo.
Make an issue with specifics you'd like to see.
https://www.youtube.com/watch?v=4LZo9ugJTWQ
